# nclh_sf_recursive_filter/dbt_project.yml

name: 'nclh_sf_recursive_filter'
version: '1.0.0'
config-version: 2

profile: 'nclh_sf_profile' # Matches profiles.yml entry

model-paths: ["models"]
macro-paths: ["macros"]

models:
  nclh_sf_recursive_filter:
    +materialized: view # Default materialization for models
    staging:
      +materialized: view
    core:
      +materialized: table
    intermediate:
      +materialized: table
    semantic:
      # Semantic layer definitions are loaded from separate YAML files in this folder

vars:
  filter_level: "none" # Default value for filter_level variable (e.g., 'brand', 'ship', 'none')
  filter_value: ""     # Default value for filter_value variable (e.g., 'Norwegian Cruise Line')